name: Deploy

on:
  push:
    branches:
      #- main
      - PM-1524-deploy-workflow
 # workflow_dispatch:
 #   inputs:
 #     docker_tag_prefix:
 #       description: "Enter the Docker Tag Prefix (e.g adhoc-test)"
 #       required: true
 #       type: string

#env:
#  ECR_REPOSITORY_URL: 673156464838.dkr.ecr.us-west-2.amazonaws.com
#  ECR_REPOSITORY_NAME: gpt-survey-summarizer
#  DOCKER_TAG_PREFIX: ${{ github.event.inputs.docker_tag_prefix }}

jobs:
  deploy:
    name: Build and Publish Docker Image
    runs-on: minafoundation-default-runners
    steps:

      - name: âš™ï¸ Set environment variables
        run: |
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
          echo "DEPLOYMENT_ROLE_NAME=$DEPLOYMENT_ROLE_NAME" >> $GITHUB_ENV
          echo "AWS_ROLE_DURATION_SECONDS=$AWS_ROLE_DURATION_SECONDS" >> $GITHUB_ENV

      - name: ðŸ”‘ Assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.DEPLOYMENT_ROLE_NAME }}
          role-session-name: ${{ env.DEPLOYMENT_ROLE_NAME }}
          role-duration-seconds: ${{ env.AWS_ROLE_DURATION_SECONDS }}

      - name: Test k8s
        run: |
          aws sts get-caller-identity
          kubectl get ns || true
          echo waiting for 120s
          sleep 120

